name = "breaktapes-app"
compatibility_date = "2024-09-23"
account_id = "b09f233e618dc7f23bcb247c947eb303"

assets = { directory = "public", html_handling = "auto-trailing-slash" }

# Production: app.breaktapes.com
# Deploy: wrangler deploy
routes = [
  { pattern = "app.breaktapes.com/*", zone_id = "7d1d8be858893e977e57b0455ed2388f" }
]

# Staging: dev.breaktapes.com
# Deploy: wrangler deploy --env staging
[env.staging]
name = "breaktapes-app-staging"
routes = [
  { pattern = "dev.breaktapes.com/*", zone_id = "7d1d8be858893e977e57b0455ed2388f" }
]
