name = "breaktapes-landing"
compatibility_date = "2024-09-23"
account_id = "b09f233e618dc7f23bcb247c947eb303"
main = "worker.js"

routes = [
  { pattern = "breaktapes.com/*", zone_id = "7d1d8be858893e977e57b0455ed2388f" }
]
