import type React from 'react'

export const sharedFormControlStyles = {
  label: {
    fontSize: 'var(--text-xs)',
    color: 'var(--muted)',
    marginBottom: '6px',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    fontFamily: 'var(--headline)',
    fontWeight: 700,
    display: 'block',
  } as React.CSSProperties,

  input: {
    width: '100%',
    background: 'linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.015)), var(--surface3)',
    border: '1px solid var(--border2)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--white)',
    fontSize: 'var(--text-compact)',
    padding: '0.72rem 0.85rem',
    fontFamily: 'var(--body)',
    boxSizing: 'border-box' as const,
    minWidth: 0,
    minHeight: '44px',
    outline: 'none',
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.02)',
  } as React.CSSProperties,

  select: {
    width: '100%',
    background: 'linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.015)), var(--surface3)',
    border: '1px solid var(--border2)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--white)',
    fontSize: 'var(--text-compact)',
    padding: '0.72rem 2.4rem 0.72rem 0.85rem',
    fontFamily: 'var(--body)',
    boxSizing: 'border-box' as const,
    minWidth: 0,
    minHeight: '44px',
    outline: 'none',
    appearance: 'none' as const,
    WebkitAppearance: 'none' as const,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.02)',
  } as React.CSSProperties,

  textarea: {
    width: '100%',
    background: 'linear-gradient(180deg, rgba(255,255,255,0.03), rgba(255,255,255,0.015)), var(--surface3)',
    border: '1px solid var(--border2)',
    borderRadius: 'var(--radius-md)',
    color: 'var(--white)',
    fontSize: 'var(--text-compact)',
    padding: '0.72rem 0.85rem',
    fontFamily: 'var(--body)',
    boxSizing: 'border-box' as const,
    minWidth: 0,
    minHeight: '88px',
    outline: 'none',
    resize: 'vertical' as const,
    boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.02)',
  } as React.CSSProperties,

  secondaryButton: {
    background: 'transparent',
    color: 'var(--muted)',
    border: '1px solid var(--border2)',
    borderRadius: 'var(--radius-md)',
    padding: '0.75rem 1rem',
    fontFamily: 'var(--headline)',
    fontWeight: 800,
    fontSize: 'var(--text-xs)',
    letterSpacing: '0.08em',
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
  } as React.CSSProperties,
}
